# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
palette = "catppuccin_mocha"

# A minimal left prompt
format = """
$os\
$character"""

# Move the rest of the prompt to the right
right_format = """$all"""

# Starship modules
[character]
format = '$symbol '
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](subtext1)"

[directory]
format = '[  ](blue)[$path]($style)[ $read_only]($read_only_style)'

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = "󰉍"
"Music" = "󱍙"
"Pictures" = ""
"Videos" = ""
"developer" = "󰲋"

[line_break]
disabled = true

[os]
format = '[$symbol]($style) '
disabled = false

[os.symbols]
Arch = "󰣇"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = '🌱 '

[cmd_duration]
format = '[⏱ $duration]($style)'

[package]
disabled = true

[time]
format = '[[  $time ](fg:text bg:surface0)]($style)'
style = "bg:surface0"
disabled = true

[username]
format = '[](fg:mauve)[ $user ]($style)'
style_user = "fg:text"
style_root = "fg:red"
show_always = true

# Palette definitions
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
